FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL


COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN apt-get update -y && apt-get install -y openssl

RUN bun install

RUN bun db:generate

RUN bun run build 

EXPOSE 8080

CMD ["bun","run","start:web"]